### ISSUE TITLE
what's the shape of output in the example?

### ISSUE THREAD

**Issue by byzhang** [tensorflow/lattice#14]
c.f.
https://github.com/tensorflow/lattice/blob/master/examples/uci_census.py#L419

**Comment by byzhang** [comment]
and also the values in the output? Thanks a lot!

**Comment by si-you** [comment]
input_calibration_layer accepts features and applies 1-D calibration per each feature and returns them. In this example, we have 15 features, so the input to this layer has a shape, [batch_size, 15], and then the output should be [batch_size, 15].

Initial output value will depend on hparam's output_min and output_max. Since it is configured to [-1, 1], the output should be a linear function of your input that maps [input_min, input_max] to [-1, 1]. But note that output keypoints are trained jointly with your upper layer DNN. So as training proceeds, the output value will change even for the same input value :).

**Comment by byzhang** [comment]
Thank you Seungil!
We need to precompute the quantiles?
And what's the effect of nodes_per_layer and layers in https://github.com/tensorflow/lattice/blob/master/examples/uci_census.py#L407

**Comment by si-you** [comment]
Yes. You need to pre-compute quantiles, but that can be done by passing the flag --compute_quantiles :).

nodes_per_layer and layers param is used in here:
https://github.com/tensorflow/lattice/blob/master/examples/uci_census.py#L424

to construct DNN.

**Comment by byzhang** [comment]
Thanks!

Thanks,
-B
